name: Build
on: 
  push:
    branches:
      - "**"
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          make all

