name: Build
on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  build:
    name: Build
    runs-on: macos-14 # to get arm64 code
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make
        run: |
          make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anti-virus
          path: build/anti-virus.zip
