name: Build
on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  build:
    name: Build
    runs-on: macos-14 # to get arm64 code
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
          ls -al /Applications/Docker.app/Contents/MacOS
          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a /Applications/Docker.app --args --unattended --accept-license
          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
          make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anti-virus
          path: build/anti-virus.zip
