name: Build
on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2.7.1
        name: Make
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          run: |
            make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anti-virus
          path: build/anti-virus.zip
