name: Release
on: 
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: |
          make all
      - uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: build/lambda.zip
          allowUpdates: true
