name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2.7.1
        name: Make
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          run: |
            make all
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build/anti-virus.zip
          allowUpdates: true
