name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make
        run: |
          make all
      - uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: build/anti-virus.zip
          allowUpdates: true
